In [15]:
import numpy as np

A = np.array([[10,20,30],[40, 50, 60]])

row = np.array([70, 80, 90]).reshape(1, 3)

B = np.concatenate((A, row), axis = 0)
print(B)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [16]:
import numpy as np

A = np.array([[10,20,30],[40, 50, 60]])

col = np.array([10000, 20000]).reshape(2, 1)

C = np.concatenate((A, col), axis = 1)
print(C)

[[   10    20    30 10000]
 [   40    50    60 20000]]


In [21]:
import numpy as np

A = np.array([[10,20,30],[40, 50, 60]])

row2 = np.array([70, 80, 90, 100, 1000]).reshape(-1, 3)
print(A)
print(row2)

# row1 = np.concatenate((A, row2), axis = 0)
print(B)

ValueError: cannot reshape array of size 5 into shape (3)

In [24]:
import numpy as np

A = np.array([[10,20,30],[40, 50, 60]])

row2 = np.array([70, 80, 90, 100, 110, 120]).reshape(-1, 3)
print(A)
print(row2)

D = np.concatenate((A, row2), axis = 0)
print(D)

[[10 20 30]
 [40 50 60]]
[[ 70  80  90]
 [100 110 120]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
