In [3]:
import numpy as np

loaded_data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

x_data = loaded_data[:, 0:-1]
t_data = loaded_data[:, [-1]]
print(x_data)
print(t_data)

[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [9]:
import numpy as np

loaded_data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

x_data2 = loaded_data[:, :-1]
t_data2 = loaded_data[:, -1]
print(x_data2)
print(t_data2)
print(t_data2.shape)
print(t_data2.ndim)

[[1 2]
 [4 5]
 [7 8]]
[3 6 9]
(3,)
1
